/* Focused checks for the new progressive enhancements. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const base=process.env.QA_ORIGIN || 'http://localhost:3128';
(async()=>{
  const browser=await chromium.launch({channel:'chrome',headless:true});
  try {
    const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
    if(process.env.AXE_SCRIPT)await page.addInitScript({content:fs.readFileSync(process.env.AXE_SCRIPT,'utf8')});
    page.on('pageerror',e=>errors.push(e.message));
    page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
    await page.goto(base+'/resources/redesign-something-old/',{waitUntil:'networkidle'});
    const steps=page.locator('[data-practice-step]');
    assert.equal(await steps.count(),3,'Prompt steps become optional checkboxes');
    await steps.first().focus();await page.keyboard.press('Space');
    assert.equal(await steps.first().isChecked(),true);
    assert.match(await page.locator('[data-practice-status]').textContent(),/1 of 3/);
    await steps.nth(1).check();await steps.nth(2).check();
    assert.match(await page.locator('[data-practice-status]').textContent(),/3 of 3/);
    await page.getByRole('button',{name:'Reset checklist'}).click();
    assert.equal(await steps.first().isChecked(),false);
    assert.equal(await steps.first().evaluate(e=>e===document.activeElement),true,'Reset restores useful focus');
    await steps.first().check();await page.reload({waitUntil:'networkidle'});
    assert.equal(await steps.first().isChecked(),false,'No checklist data persists');
    if(process.env.AXE_SCRIPT)assert.deepEqual((await page.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}}))).violations.map(v=>v.id),[]);
    await page.goto(base+'/create/',{waitUntil:'networkidle'});
    const invoker=page.locator('[data-photo-view]').first();await invoker.click();
    const viewer=page.locator('[data-media-dialog]');
    assert.equal(await viewer.getByRole('button',{name:'Next photograph'}).isVisible(),true);
    const first=await viewer.locator('[data-media-image]').getAttribute('src');
    await page.keyboard.press('ArrowRight');
    assert.notEqual(await viewer.locator('[data-media-image]').getAttribute('src'),first);
    assert.match(await viewer.locator('[data-media-status]').textContent(),/2 of 2/);
    await viewer.getByRole('button',{name:'Previous photograph'}).click();
    assert.equal(await viewer.locator('[data-media-image]').getAttribute('src'),first);
    if(process.env.AXE_SCRIPT)assert.deepEqual((await page.evaluate(()=>axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa','wcag22aa']}}))).violations.map(v=>v.id),[],'Photo gallery accessibility');
    await page.keyboard.press('Escape');
    assert.equal(await invoker.evaluate(e=>e===document.activeElement),true,'Gallery closes to original invoker');
    await page.goto(base+'/',{waitUntil:'networkidle'});
    const card=page.locator('[data-world-link]').first();await card.scrollIntoViewIfNeeded();
    const box=await card.boundingBox();await page.mouse.move(box.x+box.width*.85,box.y+box.height*.25);
    await page.waitForFunction(()=>document.querySelector('[data-world-link]').style.getPropertyValue('--card-tilt-y')!=='');
    const rotation=await card.evaluate(e=>parseFloat(e.style.getPropertyValue('--card-tilt-y')));
    assert.ok(rotation>0 && rotation<=2,'Pointer depth stays restrained');
    await page.mouse.move(1,90);
    await page.waitForFunction(()=>document.querySelector('[data-world-link]').style.getPropertyValue('--card-tilt-y')==='');
    await page.emulateMedia({reducedMotion:'reduce'});await page.mouse.move(box.x+box.width*.8,box.y+box.height*.2);
    assert.equal(await card.evaluate(e=>getComputedStyle(e).transform),'none','Reduced motion keeps cards static');
    const noJS=await browser.newPage({javaScriptEnabled:false});
    await noJS.goto(base+'/resources/redesign-something-old/');
    assert.equal(await noJS.locator('[data-practice-steps] li').count(),3,'Original instructions survive without JavaScript');
    assert.equal(await noJS.locator('[data-practice-step]').count(),0);await noJS.close();
    const touch=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
    await touch.goto(base+'/',{waitUntil:'networkidle'});
    assert.equal(await touch.locator('html').evaluate(e=>e.classList.contains('has-pointer-depth')),false,'Touch has no pointer tilt');
    await touch.goto(base+'/create/',{waitUntil:'networkidle'});await touch.locator('[data-photo-view]').first().click();
    assert.equal(await touch.locator('[data-media-dialog]').evaluate(e=>e.scrollWidth<=e.clientWidth+1),true,'Mobile gallery controls fit');
    assert.equal(await touch.locator('[data-media-close]').evaluate(e=>getComputedStyle(e).whiteSpace),'nowrap','Close label remains readable');await touch.close();
    assert.deepEqual(errors,[]);
    console.log('Passed keyboard checklist/reset/no persistence/no-JS, gallery browsing/Escape/focus, bounded card depth, touch and reduced-motion checks.');
  } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
