figma.showUI(`<!doctype html><html><head><meta charset="utf-8"><style>
body{margin:0;padding:24px;background:#F7F4EC;color:#101A33;font:14px/1.55 Inter,Arial,sans-serif}h1{font-size:24px;margin:0 0 12px}button{background:#101A33;color:#F7F4EC;border:0;border-radius:4px;padding:14px 20px;font:600 14px Arial;cursor:pointer}button:disabled{opacity:.45}textarea{width:100%;height:150px;box-sizing:border-box;margin:16px 0;font:12px monospace}small{display:block;margin:12px 0}a{color:#101A33}.inspection h1,.inspection small,.inspection>p:not(#inspection):not(#status),.inspection>button,.inspection textarea{display:none}select{max-width:360px;padding:10px;font:14px Arial}
</style></head><body><h1>Finish the HTAFL website UI</h1><p>Reuse the existing identity, components, tokens and licensed photography. Add the supporting desktop/mobile pages, immersive storyboards, form/resource states, prototype connections and handoff notes.</p><small>No network access. No inquiries sent. No production website changes. Only the intended HTAFL design file is supported.</small><button id="context">Export implementation context</button><button id="run">Complete design in this file</button><p id="status">Ready. This action adds editable native Figma layers.</p><textarea id="report" readonly aria-label="Completion report"></textarea><button id="save" disabled>Save completion report</button><p id="inspection"><label for="screen">Inspect a screen</label><br><input id="screen-id" aria-label="Review frame ID" value="8:107" style="width:130px;padding:10px"><select id="screen"></select> <button id="inspect" disabled>Inspect screen</button></p><script>
document.getElementById('context').onclick=()=>{parent.postMessage({pluginMessage:{type:'context'}},'*');document.getElementById('status').textContent='Reading the native design…';};let report=null;document.getElementById('run').onclick=()=>{document.getElementById('run').disabled=true;parent.postMessage({pluginMessage:{type:'complete'}},'*');document.getElementById('status').textContent='Building editable screens and prototype flowsâ€¦';};
onmessage=e=>{const m=e.data.pluginMessage;if(!m)return;if(m.context){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(m.context)],{type:'application/json'}));a.download='htafl-design-context.json';a.click();}document.getElementById('status').textContent=m.message;if(m.report){report=m.report;const compact={fileKey:report.fileKey,frames:report.frames.map(f=>[f.name,f.id,f.width,f.height]),frameCount:report.frameCount,reactionCount:report.reactionCount,unresolved:report.unresolved,layoutIssues:report.layoutIssues,handoffId:report.handoffId};document.getElementById('report').value=JSON.stringify(compact);document.getElementById('save').disabled=false;document.getElementById('inspect').disabled=false;for(const f of report.frames){const o=document.createElement('option');o.value=f.id;o.textContent=f.name;document.getElementById('screen').appendChild(o);}}if(m.error){document.getElementById('report').value=m.error;document.getElementById('run').disabled=false;}};
document.getElementById('screen').onchange=()=>{document.getElementById('screen-id').value=document.getElementById('screen').value;};document.getElementById('inspect').onclick=()=>{document.body.classList.add('inspection');parent.postMessage({pluginMessage:{type:'inspect',id:document.getElementById('screen-id').value}},'*');};
document.getElementById('save').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));a.download='htafl-figma-completion-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
</script></body></html>`,{width:620,height:510});
let running=false;
figma.ui.onmessage=async m=>{if(m.type==='context'){try{const context=await exportImplementationContext();figma.ui.postMessage({context,message:'Native design context exported. No canvas edits.'});}catch(e){figma.ui.postMessage({error:String(e),message:'Design context export failed.'});}return;}if(m.type==='inspect'){const n=await figma.getNodeByIdAsync(m.id);if(n&&n.type==='FRAME'&&n.parent.type==='PAGE'){await figma.setCurrentPageAsync(n.parent);n.parent.selection=[n];figma.viewport.zoom=n.width===390?1:.62;figma.viewport.center={x:n.x+n.width/2,y:n.y+(n.width===390?350:600)};figma.ui.resize(620,180);figma.ui.postMessage({message:'Inspecting '+n.name+'. Close the helper panel to view the canvas fully.'});}return;}if(m.type!=='complete'||running)return;running=true;try{const report=await completeDesign(CONFIG);figma.ui.postMessage({message:'Design generated. '+report.frameCount+' frames; '+report.reactionCount+' prototype connections. Visual review is the next step.',report});}catch(e){figma.ui.postMessage({message:'Stopped safely. Inspect the error before retrying.',error:String(e.stack||e)});}finally{running=false;}};
